blank_issues_enabled: true
contact_links:
  - name: 💬 Discussions
    url: https://github.com/mirkobertone/md2pdf/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://github.com/mirkobertone/md2pdf#readme
    about: Read the project documentation
